name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs once every hour

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the Node.js version you use locally

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the scraper script
      - name: Run scraper
        run: node scraper.js

      # Step 5: Commit and push changes
      - name: Commit and Push changes
        run: |
          git config --global user.name "PFisk"
          git config --global user.email "pfisk@users.noreply.github.com"
          git add data/fireballs-new.json
          git add data/fireballs-full.json
          git commit -m "Update fireball data!" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
